# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e608ee6ad1b47b0470f4accf621edc5c848a9aa302de7c9df5e593e610e60482a09ef553eabb02c037b45d10c2742c195893188c84ea858e35757f138feb3faa

test:
  secret_key_base: b8a3c1a1f98efa88ea1746ead78c3bd9015eb7082476854825d0b5b2297ae2d57f424a8480fbc98e14275bd93affb8669a22722fbdbf754f2354d7a1b20f1202

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
